### ISSUE TITLE
make sure crafters can get access to ticketing

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#18]
people with the production flag should have access to tickets, but not sets and schedules.

**Comment by perlDreamer** [comment]
Full access or view access only?

**Comment by rizen** [comment]
They need full access to the ticketing system.

**Comment by perlDreamer** [comment]
I'm going to need your help with this.  None of the pages that we've created have any kind of middleware for ownership.  When I start adding them in, then I start getting all kinds of wonky errors from H3.  Googling the errors isn't telling me anything useful.

**Comment by rizen** [comment]
OK, I’ve got a couple of hours in the morning tomorrow so let’s work on it then

**Comment by perlDreamer** [comment]
Workaround installed for this.
