### ISSUE TITLE
3D printer hardware items don't have a status

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#20]
It's possible that no hardware items have a status.

**Comment by perlDreamer** [comment]
I'm not sure what you mean here.  Do you mean that there are hardware items that do not have a status and need them, or that we need a 3rd status different from "In use" and "Retired", or something else altogether?

**Comment by rizen** [comment]
No, I mean when I was showing them the system the 3d printers have no status dropdown options
<img width="482" alt="Screenshot 2024-10-28 at 6 03 55 PM" src="https://github.com/user-attachments/assets/17449f26-3ecd-49c2-b86b-bdc8fab1cb26">

see here: https://www.thegamecrafter.com/hardwareitem/HardwareItemvCIq5l_

And nothing else does either: 

<img width="414" alt="Screenshot 2024-10-28 at 6 04 31 PM" src="https://github.com/user-attachments/assets/aaa9a1dc-84be-4f6e-b4c5-b8cfd160399b">

https://www.thegamecrafter.com/hardwareitem/HardwareItemvBieE7Y
