### ISSUE TITLE
an extra comment is showing up on all new tickets. figure out why

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#21]
<img width="487" alt="Screenshot 2024-10-28 at 3 29 56 PM" src="https://github.com/user-attachments/assets/ca98a29c-4e22-414b-aa00-437f0c0e837e">

**Comment by perlDreamer** [comment]
The problem here is that the Ticket is fetching ALL the Remarks and Files (across all tickets), instead of only its own.
