### ISSUE TITLE
add the resolution field to new ticket creation

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#22]
There are many tickets that are essentially just log entries, like "Changed the ink in KM B". Those have to be logged, but there's no further work to be done. Therefore they need a way to submit a ticket that is immediately closed.

**Comment by perlDreamer** [comment]
In addition to the resolution field, do we also need time spent (resolutionMinutes)?

**Comment by rizen** [comment]
sure, let's put it there too.

**Comment by perlDreamer** [comment]
Fixed.
