### ISSUE TITLE
deploy the new maintenance ticketing system

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#23]
this is your reminder to deploy this bad boy. As part of deployment make sure you link to the individual pages from the nav on TGC, but don't just get rid of the nav on TGC, because it does have the "site ticket" item that everyone will still need, but is not on this site

**Comment by perlDreamer** [comment]
Also to change over the 3D Printer dashboard and Big Laser dashboard to pull items from the new site instead of maintenance_items_include.tt

**Comment by rizen** [comment]
Oh good call. And probably search the code base for anything else that might need to do that. Like the laser dashboard.

**Comment by perlDreamer** [comment]
Create new api key, public key for Admin so that the farms can see equipment and sets.

**Comment by perlDreamer** [comment]
Deployed and tested the integration with TGC.
