### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by vrby** [plainblack/TGCv#31]
TGC_Production has all the same privileges that mechanics do which means they can adjust/add schedules, add new hardware, delete tickets, etc.  This probably should not be the case.  I know we have 1 permission level currently and you have to be a maintenance manager.  Just throwing this out as a possible issue long term. 

Jamie

**Comment by perlDreamer** [comment]
TGC_Production has the Maintenance Manager permission in the TGC account.  People with Production Manager permission can see some things on the site, and create/edit tickets.

**Comment by perlDreamer** [comment]
@vrby If Production Manager has too much power on the the new maintenance site, just remove the Maintenance Manager privilege from their account.  That was previously needed to give them view permissions, but isn't any longer.

**Comment by rizen** [comment]
removed
