### ISSUE TITLE
ArtieCee links should target

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#38]
When ArtieCee posts to slack, clicking on the link opens a browser window in the background, but it looks like nothing happens. I'm wondering if we can put a target on the link or something to bring the browser to the foreground when clicking on the link in slack.

**Comment by perlDreamer** [comment]
I can't duplicate this on Chrome.  When I click on a link, it brings Chrome into focus, opens a tab and that tab has the URL for the ticket.

Is this specific to Safari?  Is it happening on desktops or mobile or tablets or something else?

**Comment by rizen** [comment]
I'm noticing it on Safari on Mac. When I click on other links in Slack it also happens on Safari, so I guess this is a bug with Safari and Slack.
